### ISSUE TITLE
Not able to get Unicode support ("\alpha<TAB>") and "filetype plugin indent on" to work together

### ISSUE THREAD

**Issue by skrisna** [JuliaLang/julia-vim#47] opened 2015-04-21 08:03 UTC
I am not able to get Unicode support ("\alpha<TAB>") and "filetype plugin indent on" to work together. When I set "filetype plugin indent on" in my vimrc, typing "\alpha<TAB>" does not insert anything (either tab or character). On the other hand, if I set "filetype plugin on", I am able to get the right Unicode character inserted when I type "\alpha<TAB>" but then indentation does not work. My mimimal vimrc file that exhibits this problem is shown below. I am using Vim7.4/Windows/7/x64.

set nocompatible

filetype off
set rtp+=~/vimfiles/bundle/Vundle.vim/
let path='~/vimfiles/bundle'
call vundle#begin(path)
Plugin 'gmarik/Vundle.vim'
Plugin 'cocopon/iceberg.vim'
Plugin 'JuliaLang/julia-vim'
Plugin 'ervandew/screen'
call vundle#end()

colorscheme iceberg
if has('gui_running')
    set guifont=Dejavu\ Sans\ Mono:h12
endif
set encoding=utf-8
syntax on
filetype plugin on

**Comment by carlobaldassi** [comment] 2015-04-22 21:22
I can't reproduce the issue on my machine. I copied your setup, changed the last line to `filetype plugin indent on` and everything works as it should.

Must be a windows issue.

**Comment by skrisna** [comment] 2015-04-23 00:01
Hi Carlo,

You are right. This is an issue only the Gvim/Windows version. I checked ubuntu both using the GTK version and the terminal version and there were not problems. I am not sure why the problem with the Windows version exists. 

Thanks for checking.

**Comment by carlobaldassi** [comment] 2015-04-23 00:27
Just to check: does the autosub feature work at least? I.e. putting this line into your vimrc:

```
let g:latex_to_unicode_auto = 1
```

and then typing away. It should substitute latex command on the fly.

**Comment by skrisna** [comment] 2015-04-23 01:12
Auto substitution works! So here is a summary of the problem:

filetype plugin indent on
let g:latex_to_unicode_auto = 1
Auto-substitution: PASS, i.e. proper symbols \alpha are inserted etc
Tab insert: FAIL

filetype plugin on
Auto-substitution: PASS (w/ let g:latex_to_unicode_auto = 1)
Tab insert: PASS 






Thanks for the suggestion.

**Comment by carlobaldassi** [comment] 2015-04-23 09:22
Ah good. Also: if that is the minimal vimrc file which exhibits the issue, does it mean that the problem goes away if you comment out the `cocopon/iceberg.vim` or the `ervandew/screen` plugins?
(It seems weird that `iceberg` would do anything, isn't it just a colorscheme?)

**Comment by skrisna** [comment] 2015-04-23 18:30
Please don't read too much into the term 'minimal'. I used the term after I removed most of my other vimrc stuff. 

I disabled cocopon/iceberg and ervandew/screen and am still getting issues discussed earlier. So the problem seems to be with julia-vim itself.

**Comment by carlobaldassi** [comment] 2015-04-23 18:31
Ok good to know, thanks.

**Comment by carlobaldassi** [comment] 2015-04-23 19:15
I hope this is fixed now. If not please comment and I'll reopen.

**Closed** 2015-04-23 19:14 UTC

**Comment by skrisna** [comment] 2015-04-23 19:20
How do I test this? PluginInstall (from Vundle) did not pull anything. Should I wait for a git push from you?

**Comment by carlobaldassi** [comment] 2015-04-23 19:23
Should be `:PluginUpdate` I think. It's already pushed.

**Comment by skrisna** [comment] 2015-04-23 19:25
Thanks Carlo. Works great.
